@startuml UC-04-s_diagram
title Activity - диаграмма по UC-04-Оформление заказа
start
    :Клиент на странице корзины;
    if (Корзина заполнена?) then (**Да**     )
        :Клиент нажимает на кнопку
               **"Оформить заказ"**;
        :    Перенаправляем клиента \nна страницу оформления заказа;
        :Клиенту открывается страница оформления заказа 
                      и предлагается заполнить данные;
        note right
            Поля для оформления заказа
                - Адрес доставки
                - Способ доставки
                - ФИО клиента
                - email
                - Номер телефона;
        ----
                Заполнение полей
                может быть как самостоятельным,
                так и автоматическое заполнение полей, 
                после авторизации.
        end note
        : Клиент ставит галочку на удобном способе оповещения;
        note left
            Способы оповещения о статусе заказа:
            - email
            - Номер телефона
        end note
        repeat :Клиент проверяет данные; 
            :Нажимает на кнопку **"Заказать"**;
        
        backward :Выводим сообщение об ошибке 
        до тех пор пока клиент ее не исправит;
            note right
                Возможные варианты ошибок
                - Неправильно заполненное поле
                - Незаполненное обязательное поле
            end note
        repeat While (Данные корректные?) is (**Нет**) not (**Да**)
        
        :Переход на страницу оплаты;
        :Клиент выбирает желаемый способ оплаты
                         и нажимает "Оплатить";
        if (Оплата прошла успешно?) then (**Да**     )
            fork
                :Отправляем уведомление о создании заказа 
                на выбранный способ оповещения;
            fork again
                :Отправляем чек об оплате на указаный email;
            end merge

        else (     **Нет**)
            :Выводим сообщение об ошибке;
            note right
            Возможные варианты ошибок:
            - Некорректно введены данные карты
            - Отказ авторизации платежа
            - Ошибка сервера и т.д.
        end note
            end
        endif
        
            stop
    else (     **Нет**)
        :     Выводим сообщение "Корзина пуста" \nи предлагаем вернуться в каталог товаров;
        end
    endif
@enduml