@startuml UC-04-s_diagram
title Sequence - диаграмма по UC-04-Оформление товара
actor Клиент
participant Система
activate Клиент
activate Система
Клиент -> Клиент :Проверяет товары в корзине, \nих количество и стоимость

Клиент -> Система :Нажимает на кнопку \n"Оформить заказ"
Система --> Клиент :Перенаправляет на страницу оформления заказа и \nпредлагает заполнить данные

Клиент -> Клиент :Заполняет данные \nдля оформления заказа
Клиент -> Клиент :Ставит галочку на удобном способе \nуведомления о статусе заказа
Клиент -> Клиент :Проверяет введенные данные

Клиент -> Система :Нажимает на кнопку \n"Заказать"
Система --> Клиент :Проверяет введенные данные и \nотправляет на страницу оплаты

Клиент -> Система :Выбирает нужный способ оплаты и \nнажимает "Оплатить"
Система --> Клиент :Осуществляет оплату заказа
Система --> Клиент : Отправляет уведомление о создании заказа \nвыбранным способом уведомления
Система --> Клиент : Отправляет чек об оплате заказа \nна указанный email
@enduml