@startuml UC-03-uc_diagram
title Use Case - диаграмма по UС-03-Поиск товаров по каталогу
actor Клиент
  Клиент --> (Просмотр каталога товара)
  (Просмотр каталога товара) ..> (Изучение карточки товара): <<include>>

package "Изучение карточки товара" {
  (Просмотр изображений товара)
  (Просмотр информации о товаре)
  (Просмотр отзывов и рейтинга товара)
}
  (Просмотр информации о товаре) ...> (Просмотр описания товара): <<include>>
  (Просмотр информации о товаре) ...> (Просмотр характеристик товара): <<include>>

  package "Поиск товара" {
  (Ввод запроса в поисковую строку)
  (Выбор категории товара)
}
(Просмотр каталога товара) .> (Поиск товара): <<include>>
(Поиск товара) <.. (Фильтрация): <<extend>>
(Поиск товара) <.. (Сортировка): <<extend>>

  Клиент -> (Добавление товара в корзину)
@enduml

